FROM public.ecr.aws/docker/library/node:20-alpine

WORKDIR /app
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml* svelte.config.js vite.config.ts tsconfig.json ./
RUN pnpm install
COPY . .

EXPOSE 5173

CMD ["pnpm", "dev", "--host", "0.0.0.0", "--port", "5173"]