services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
      args:
        MODE: ${MODE:-dev}
    ports:
      - "5173:5173"   # dev mode
      - "80:80"       # prod mode
      - "443:443"     # prod mode
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api

  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
      args:
        MODE: ${MODE:-dev}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
    command: >
      sh -c "if [ '$${MODE}' = 'prod' ];
             then gunicorn -k uvicorn.workers.UvicornWorker main:app -b 0.0.0.0:8000;
             else uvicorn main:app --host 0.0.0.0 --port 8000 --reload;
             fi"
