apiVersion: v1
kind: Pod
metadata:
  name: dnd-westmarches
  labels:
    app: dnd-westmarches
spec:
  containers:
    - name: backend
      image: localhost/dnd-backend:latest
      ports:
        - containerPort: 8000
      env:
        - name: DATABASE_URL
          value: "sqlite:////data/app.db"
        - name: PYTHONPATH
          value: "/app"
        - name: MODE
          value: "prod"
      volumeMounts:
        - name: backend-data
          mountPath: /data
    - name: frontend
      image: localhost/dnd-frontend:latest
      ports:
        - containerPort: 80
          hostPort: 9080
        - containerPort: 443
          hostPort: 9443
      env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-token
              key: token
              optional: true
      volumeMounts:
        - name: caddy-data
          mountPath: /data
        - name: caddy-config
          mountPath: /config
  volumes:
    - name: backend-data
      persistentVolumeClaim:
        claimName: dnd-backend-data
    - name: caddy-data
      persistentVolumeClaim:
        claimName: dnd-caddy-data
    - name: caddy-config
      persistentVolumeClaim:
        claimName: dnd-caddy-config
